export interface Movie{
	"Title": String,
	"Year": Number,
	"Rated": String,
	"Released": String,
	"Runtime": String,
    "Genre": [String],
	"Director": String,
	"Writer": String,
    "Actors": [String],
	"Plot": String,
	"Language": String,
	"Country": String,
	"Awards": String,
	"Poster": String,
	"Metascore": String,
	"imdbRating": Number,
	"imdbVotes": Number,
	"imdbID": String,
	"Type": String,
	"Top250": Number
}